import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  bannerCont: {},
  imageBanner: {
    flex: 1,
    display: "flex",
    height: 350,
    backfaceVisibility: "hidden",
  },
  detailsCont: {
    position: "absolute",
    display: "flex",
    paddingTop: 70,
    paddingHorizontal: 20,
    // justifyContent: "center",
    // alignItems: "center",
    backgroundColor: "transparent",
    height: "100%",
    width: "100%",
    zIndex: 3,
  },
  title: {
    color: "#fff",
    fontFamily: "monospace",
    backgroundColor: "rgba(1,1,1,0.4)",
    fontSize: 20,
    paddingLeft: 5,
    paddingRight: 5,
    borderRadius: 3,
    maxWidth: "80%",
    marginBottom: 20,
    fontWeight: "bold",
  },
  description: {
    display: "flex",
    // textAlign: "center",
    backgroundColor: "rgba(1,1,1,0.4)",
    color: "#fff",
    fontFamily: "monospace",
    fontSize: 11,
    padding: 5,
    borderRadius: 3,
    width: "65%",
    lineHeight: 15,
  },
  iconsCont: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    height: 35,
    width: 150,
    marginBottom: 15,
    paddingLeft: 5,
  },
  play: {},
  linearGrad: {
    position: "absolute",
    bottom: 0,
    height: "40%",
    width: "100%",
  },
});
